### PR TITLE
Add an option to determine how the caps lock key is handled

### PR DESCRIPTION
**Pull request by intentionally-left-nil**
The current default behavior of the caps lock is to automatically
ignore it. This PR adds a configuration option to remove this limiting
behavior.

The fix is to add an options blob to the constructor (more things could
be added in the future as needed). And then this is consumed inside
_characterFromEvent.

---

This change is [Reviewable](https://reviewable.io/reviews/ccampbell/mousetrap/349)

### CODE REVIEW

**Comment by AnilRedshift** [comment]
Addresses https://github.com/ccampbell/mousetrap/issues/350

**Comment by AnilRedshift** [comment]
@ccampbell What do I need to do to get some forward progress on this (and my other PR)?

**Comment by DustinWehr** [comment]
Not a maintainer, but tried the new PR Review out with your PR. I think the diff for mousetrap.js is messed up? Maybe it would help if you moved _characterFromEvent back to above the Mousetrap constructor, whatever it takes to make the diff actually show the differences within _characterFromEvent.

**Comment by AnilRedshift** [comment]
@DustinWehr

The function was moved because I need access to `self` and thus `_characterFromEvent` needed to move to be within the creator.

**Comment by DustinWehr** [comment]
@AnilRedshift sorry I didn't even notice that the indentation level was different.

**Pull request closed without merging**
