### PR TITLE
Return false if element is null to handle webcomponentsjs polyfill.

### LINKED ISSUE #274: _belongsTo error due to element being null
Hi,

I'm developing some features on an app, and I have them working on Chrome, but now I am testing on Firefox I am getting an error.

The issue seems to be in the _belongsTo() function which is recursive. After several iterations, it calls itself with the element parameter as null - ie element.parentNode is null.

I've not figured out what is wrong, but I am suspecting it is something to do with the webcomponents implementation of shadow-dom - or lack thereof - that is certainly one significant difference between chrome and firefox, and since thie _belongsTo() function seems to be ascending the DOM tree, then perhaps it is related.

It'd be great to get some opinion of how this problem can be worked-around.

In the meantime, I'll see if I can reduce my code into a simple test case.

Thanks,

Max.

webcomponentsjs#0.5.2
mousetrap#1.5.2
polymer#0.5.5

stack trace :
> console.trace():
<anonymous> debugger eval code:1
_belongsTo() mousetrap.js:421
_belongsTo() mousetrap.js:421
_belongsTo() mousetrap.js:421
_belongsTo() mousetrap.js:421
_belongsTo() mousetrap.js:421
_belongsTo() mousetrap.js:421
Mousetrap.prototype.stopCallback() mousetrap.js:970
_fireCallback() mousetrap.js:601
Mousetrap/self._handleKey() mousetrap.js:666
Mousetrap.prototype.handleKey() mousetrap.js:983
_handleKeyEvent() mousetrap.js:726
invoke() webcomponents.js:1070
dispatchBubbling() webcomponents.js:1024
dispatchEvent() webcomponents.js:998
dispatchOriginalEvent() webcomponents.js:953

### PR DESCRIPTION
**Pull request by davidmaxwaterman**
Fixes #274

I hope this is what you had in mind.

### CODE REVIEW

**Comment by davidmaxwaterman** [comment]
Hi, I'd like to stop using a clone of this repository if possible. Any chance of this getting merged? Thanks.

**Comment by devinivy** [comment]
This looks right to me– a simple, crucial fix.  Would love a release!

**Comment by ccampbell** [comment]
Ah my bad! I totally forgot.  Merging now...

**Comment by devinivy** [comment]
Thanks much!

**Comment by ccampbell** [comment]
I will publish a new tag here and on npm and on the mousetrap site in a few minutes

**Pull request merged**
